"""Seed rows matching honorifics.md. Used on empty table, not parsed from markdown."""

# (tokens, role, abbreviation)
HONORIFIC_SEED: tuple[tuple[str, str, str], ...] = (
    ("Bhai Sahib Bhai", "prefix", "BHB"),
    ("Bibi Sahib Bibi", "prefix", "BSB"),
    ("Singh Sahib", "prefix", "S.S."),
    ("Sardar Bahadur", "prefix", "S.B."),
    ("Sardar Sahib", "prefix", "S. Sahib"),
    ("Bhai Sahib", "prefix", "B.S."),
    ("Bibi Sahib", "prefix", "Bibi S."),
    ("Sant Baba", "prefix", "Sant Baba"),
    ("Doctor", "prefix", "Dr."),
    ("Professor", "prefix", "Prof."),
    ("Reverend", "prefix", "Rev."),
    ("Honourable", "prefix", "Hon."),
    ("Honorable", "prefix", "Hon."),
    ("Dr", "prefix", "Dr."),
    ("Prof", "prefix", "Prof."),
    ("Rev", "prefix", "Rev."),
    ("Hon", "prefix", "Hon."),
    ("Fr", "prefix", "Fr."),
    ("Father", "prefix", "Fr."),
    ("Sr", "prefix", "Sr."),
    ("Sister", "prefix", "Sr."),
    ("Capt", "prefix", "Capt."),
    ("Captain", "prefix", "Capt."),
    ("Col", "prefix", "Col."),
    ("Colonel", "prefix", "Col."),
    ("Gen", "prefix", "Gen."),
    ("General", "prefix", "Gen."),
    ("Lt", "prefix", "Lt."),
    ("Lieutenant", "prefix", "Lt."),
    ("Maj", "prefix", "Maj."),
    ("Major", "prefix", "Maj."),
    ("Sgt", "prefix", "Sgt."),
    ("Sergeant", "prefix", "Sgt."),
    ("Sir", "prefix", "Sir"),
    ("Dame", "prefix", "Dame"),
    ("Lord", "prefix", "Lord"),
    ("Lady", "prefix", "Lady"),
    ("Bhai", "prefix", "Bhai"),
    ("Bibi", "prefix", "Bibi"),
    ("Baba", "prefix", "Baba"),
    ("Mata", "prefix", "Mata"),
    ("Sant", "prefix", "Sant"),
    ("Gyani", "prefix", "Gyani"),
    ("Giani", "prefix", "Gyani"),
    ("Mahant", "prefix", "Mahant"),
    ("Jathedar", "prefix", "Jath."),
    ("Granthi", "prefix", "Granthi"),
    ("Kathakar", "prefix", "Kathakar"),
    ("Ragi", "prefix", "Ragi"),
    ("Sardar", "prefix", "S."),
    ("Sardarni", "prefix", "Sdn."),
    ("Ustad", "prefix", "Ustad"),
    ("Pandit", "prefix", "Pt."),
    ("Pundit", "prefix", "Pt."),
    ("Pt", "prefix", "Pt."),
    ("Swami", "prefix", "Swami"),
    ("Sri", "prefix", "Sri"),
    ("Shri", "prefix", "Sri"),
    ("Smt", "prefix", "Smt."),
    ("Shrimati", "prefix", "Smt."),
    ("Kumari", "prefix", "Km."),
    ("Maulana", "prefix", "Maulana"),
    ("Hafiz", "prefix", "Hafiz"),
    ("ji Maharaj", "suffix", ""),
    ("jee", "suffix", ""),
    ("ji", "suffix", ""),
    ("sahiba", "suffix", ""),
    ("sahib", "suffix", ""),
)
